apiVersion: v1
kind: Pod
metadata:
    name: app-html
    labels:
        app: app-html
spec:
    container:
    - name: app-html
        image: httpd:latest
        ports:
        - containerPort: 80
