#!bin/bash

echo "Criando diretorios..."

echo "Publico, adm, ven, sec"

mkdir /publico
mkdir /adm
mkdir /ven
mkdir /sec

echo "Criando grupos..."

echo "GRP_ADM, GRP_VEN, GRP_SEC"

groupadd GRP_ADM
groupadd GRP_VEN
groupadd GRP_SEC

echo "Criado usuarios..."

echo "Senha expira em 3 dias"

useradd carlos -c "Usuario ADM" -s /bin/bash -m -p $(openssl passwd Senha123) -G GRP_ADM && passwd carlos -n 3
useradd maria -c "Usuario ADM" -s /bin/bash -m -p $(openssl passwd Senha123) -G GRP_ADM && passwd maria -n 3
useradd joao -c "Usuario ADM" -s /bin/bash -m -p $(openssl passwd Senha123) -G GRP_ADM && passwd joao -n 3

useradd debora -c "Usuario VEN" -s /bin/bash -m -p $(openssl passwd Senha123) -G GRP_VEN && passwd debora -n 3
useradd sebastiana -c "Usuario VEN" -s /bin/bash -m -p $(openssl passwd Senha123) -G GRP_VEN && passwd sebastiana -n 3
useradd roberto -c "Usuario VEN" -s /bin/bash -m -p $(openssl passwd Senha123) -G GRP_VEN && passwd roberto -n 3

useradd josefina -c "Usuario SEC" -s /bin/bash -m -p $(openssl passwd Senha123) -G GRP_SEC && passwd josefina -n 3
useradd amanda -c "Usuario SEC" -s /bin/bash -m -p $(openssl passwd Senha123) -G GRP_SEC && passwd amanda -n 3
useradd rogerio -c "Usuario SEC" -s /bin/bash -m -p $(openssl passwd Senha123) -G GRP_SEC && passwd rogerio -n 3

echo "Assosiando grupos..."

chown root:GRP_ADM /adm
chown root:GRP_VEN /ven
chown root:GRP_SEC /sec

echo "Fornecendo permissoes..."

chmod 777 /publico
chmod 770 /adm
chmod 770 /ven
chmod 770 /sec

echo "Checagem do script"


cat /etc/group | grep GRP_*
ls -l

echo "Fim."
